[package]
name = "ryzenadj-ffi"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = { workspace = true }

[build-dependencies]
cc = { workspace = true }
bindgen = { workspace = true }
